ALTER TABLE "Game" ADD COLUMN "communityPlayers" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE "CollectionGame" ADD COLUMN "communityPlayers" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
